### ISSUE TITLE
Conan package is not published in the registry

### ISSUE THREAD

**Issue by Fohlen** [google/fruit#72]
Howdy folks! We are using fruits @ inexorgame and we noticed that your package is not yet uploaded to the [conan central repository](https://bintray.com/conan/conan-center)! It would be nice to have it so we could require upon it (currently we copied the conanfile)

Greetings & thanks for the amazing work!

**Comment by poletti-marco** [comment]
Sounds reasonable, I'm looking into it.
I'll update this issue when it's published.

**Comment by poletti-marco** [comment]
Getting there. I've now published Fruit 3.4.0 as a Conan package on Bintray:
https://bintray.com/google/fruit/fruit%3Agoogle

In the following 16 combinations:

* Built on Linux/Windows
* With/Without Boost as a dependency
* As a static/dynamic library
* Debug/Release configuration

Now I just need to get this package added to Conan Central.
I'll close this issue once that's done.

**Comment by Croydon** [comment]
Hi @poletti-marco! 

Fruit is still not included into conan-center, any news on this? If you are logged-in into Bintray the Fruit package page contains a "Add to conan center" buton
![linkedto](https://user-images.githubusercontent.com/1593194/50578457-db33ae00-0e3a-11e9-9354-641342e6d00a.PNG)

Also how got the Conan packages build and uploaded? Is there some automation already?

I'm part of [Bincrafters](https://github.com/bincrafters), a group which is focused on packaging projects for Conan and we are maintaining [templates](https://github.com/bincrafters/conan-templates-upstream) which Fruit could use to automate the building and uploaded.

Please let me know if you have any questions or need help with Conan support 😄

**Comment by poletti-marco** [comment]
Sorry about the delay, I contacted the person at Google with permissions for adding stuff to Conan Center but I haven't heard back and I forgot to follow up. I'll check back with them to get this published.

> Also how got the Conan packages build and uploaded? Is there some automation already?

No, this is not currently automated.

> I'm part of Bincrafters, a group which is focused on packaging projects for Conan and we are maintaining templates which Fruit could use to automate the building and uploaded.

Sounds interesting. I'll look into this when I have some time.
I've now opened https://github.com/google/fruit/issues/82 to track that.

> Please let me know if you have any questions or need help with Conan support smile

Thanks! I'll let you know if I hit some issues when I try setting up the automation.
Very appreciated.
